// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjBtmJ1_zJm9BYKqqN1skLPoqEYXXLZA',
    appId: '1:346244303067:android:3880edc2ed0845e99f64fe',
    messagingSenderId: '346244303067',
    projectId: 'shaadiapp-ac9ac',
    databaseURL: 'https://shaadiapp-ac9ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shaadiapp-ac9ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6hxqqZdDE3Q3rGMSQcp1Mu0AwD38c08',
    appId: '1:346244303067:ios:0f4e34a5eafe15449f64fe',
    messagingSenderId: '346244303067',
    projectId: 'shaadiapp-ac9ac',
    databaseURL: 'https://shaadiapp-ac9ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shaadiapp-ac9ac.appspot.com',
    iosClientId: '346244303067-btvvjcvhuiu4134k3geaj0urlgsbtpoq.apps.googleusercontent.com',
    iosBundleId: 'com.shadiapp.shadi',
  );
}
